### ISSUE TITLE
Example - Class and Goals

### ISSUE THREAD

**Issue by LiviaFResende** [LiviaFResende/22_05_18-and-20_Git_Activity#1]
## My Goals

-[ ] Learn how to use Issues on GitHub

@LiviaFResende is responsible for update this webpage.

**Comment by ghost** [comment]
Hi! I can see that you used the "help wanted" label, so I'm just typing something here to see what happens ; )

**Comment by LiviaFResende** [comment]
> Hi! I can see that you used the "help wanted" label, so I'm just typing something here to see what happens ; )

Hey I used the 3 dots on top of your text, to reply to your comment.

I would recommend you to click in the file and make the changes proposed in the file, this way you can open a Pull Request after you change de file.

Did you receive my message? Please confirm with me, thank you!

**Comment by ghost** [comment]
I can see it now - sorry I didn't check it earlier!

**Comment by LiviaFResende** [comment]
> I can see it now - sorry I didn't check it earlier!

:-) Have a great weekend!! See ya
